### ISSUE TITLE
nocchi wont accept decimals in input

### ISSUE THREAD

**Issue by BigEBankston** [arya-s/nocchi#1]
When typing i.e "nocchi 1.2 jpy to usd" she doesn't convert or answer while doing "nocchi 3500 yen to usd" would return "@user, 3500 JPY = 33.70 USD" which implies you should be able to use decimals as well.

**Comment by arya-s** [comment]
Thanks, will fix!

**Comment by arya-s** [comment]
Added this feature, should work now.
