### ISSUE TITLE
/iineparty and /akatsukiend audio emotes

### ISSUE THREAD

**Issue by dude22072** [arya-s/nocchi#14]
newrandomage requested /iineparty and /akatsukiend audio emotes.

https://www.dropbox.com/s/53ghawdzpsfw2wm/iineparty.mp3?dl=0 (30 seconds long)
https://www.dropbox.com/s/4c05xc41i36yu6e/akatsukiend.mp3?dl=0 (17 seconds long)

**Comment by arya-s** [comment]
These are too long, audio emotes should be emotes, not sound clips.
