### ISSUE TITLE
Enforce linting via eslint

### ISSUE THREAD

**Issue by arya-s** [arya-s/nocchi#40]

**Comment by REPTILEHAUS** [comment]
Might be a silly question but do tslint rules work for eslint ? if so I can commit my extensive tslint file

**Comment by arya-s** [comment]
Hm, not sure. We don't want to be too strict with the linting. the actual eslint config can be lax, we will adapt it. Just getting it in there is the task.

**Comment by sschadwick** [comment]
PR submitted
