### ISSUE TITLE
Add .mp3 to /maayanyan

### ISSUE THREAD

**Issue by Voltix** [arya-s/nocchi#9]
https://www.dropbox.com/s/w80ydqrn70n3nbq/nyannyan_3.mp3?dl=0 Is the MP3, should work ok

Also remove the v in gifv so its just .gif

**Comment by Voltix** [comment]
or https://drive.google.com/file/d/0B0Y3xv_rsfTMNmVud0kyemlHaHc/view?usp=sharing for the mp3, whichever u prefer

**Comment by dude22072** [comment]
#11
